name: Build nncd

on:
  push:
    branches:
    - $default-branch
    - 'release/**'
    - 'feature/**'
  pull_request:
    branches:
    - $default-branch
    - 'release/**'
    - 'feature/**'

jobs:
  web-page-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.15.0]

    steps:
    - name: clone nnc-desktop
      uses: actions/checkout@v4

    - name: setup for Node v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: restore npm ci cache
      id: npm-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-web-page-linux-${{ hashFiles('local_editor/web_component/*/package-lock.json') }}

    - name: build pages (make build-web-page)
      run: |
        mkdir ./build
        cp -r nnc-web/common ./build/
        cp -r nnc-web/web ./build/
        cp -r local_editor ./build/
        cp -rf ./build/local_editor/web_component/local_editor_web/* ./build/web/
        cp -rf ./build/local_editor/web_component/local_editor_editor ./build/new_editor
        cp -rf ./build/local_editor/web_component/local_editor_top ./build/top
        pushd ./build/local_editor
        bash init_build.sh
        popd
        cp -r ./build/top/dist/assets ./build/dist/console/
        cp -r ./build/top/dist/project ./build/dist/console/
        cp -r ./build/local_editor/resource/docs ./build/dist/console/
        cp ./build/common/favicon.ico ./build/dist/console/
        rm -rf ./build/dist/console/lib/dummy
        mv ./build/dist/console ./
        rm -rf ./build

    - name: save npm ci cache
      id: npm-cache-save
      uses: actions/cache/save@v4
      with:
        path: ~/.npm
        key: ${{ steps.npm-cache-restore.outputs.cache-primary-key }}

    - name: upload built pages
      uses: actions/upload-artifact@v4
      with:
        name: console-pages
        path: ./console/
        retention-days: 1


  app-linux-cpu:
    runs-on: ubuntu-latest
    needs: web-page-linux

    steps:
    - name: checkout nnc-desktop
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: console-pages
        path: ./console/

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: setup for python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        echo pythonLocationx
        echo ${{ env.pythonLocation }}
        pip install -U pip
        pip install nnabla==1.39.0 nnabla_converter==1.39.0
        pip install -r local_editor/requirements.txt
        pip install local_editor/runner_component/tools/console_cli/*.whl

    - name: make cpu deb
      run: |
        mkdir ./build
        cp -r ./electron_app ./build/
        wget https://nnabla.org/pkg/nncd-opt-ex.zip -O ./build/electron_app/opt-ex.zip || true
        cp -r ./console ./build/electron_app/
        cp -r ./local_editor/python_modules ./build/electron_app/py/server
        cp -r ./local_editor/runner_component/core ./build/electron_app/py/connector
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/server/
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/connector/
        cp -r ${{ env.pythonLocation }} ./build/electron_app/python_bundles
        rm -f ./build/electron_app/python_bundles/Python-3.*.tgz
        pushd ./build/electron_app
        npm ci
        npm run linux-cpu-deb
        popd
        mv ./build/electron_app/dist ./
        rm -rf ./build

    - name: upload built cpu deb
      uses: actions/upload-artifact@v4
      with:
        name: linux-cpu-deb
        path: ./dist/*.deb
        retention-days: 1

  app-linux-gpu:
    runs-on: ubuntu-latest
    needs: web-page-linux

    steps:
    - name: checkout nnc-desktop
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: console-pages
        path: ./console/

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: setup for python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        echo pythonLocationx
        echo ${{ env.pythonLocation }}
        pip install -U pip
        pip install https://nnabla.org/whl/nnabla_ext_cuda_alllib/nnabla_ext_cuda_alllib-1.39.0-cp310-cp310-manylinux_2_28_x86_64.whl
        pip install nnabla_converter==1.39.0
        pip install -r local_editor/requirements.txt
        pip install local_editor/runner_component/tools/console_cli/*.whl

    - name: make gpu deb
      run: |
        mkdir ./build
        cp -r ./electron_app ./build/
        wget https://nnabla.org/pkg/nncd-opt-ex.zip -O ./build/electron_app/opt-ex.zip || true
        cp -r ./console ./build/electron_app/
        cp -r ./local_editor/python_modules ./build/electron_app/py/server
        cp -r ./local_editor/runner_component/core ./build/electron_app/py/connector
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/server/
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/connector/
        cp -r ${{ env.pythonLocation }} ./build/electron_app/python_bundles
        rm -f ./build/electron_app/python_bundles/Python-3.*.tgz
        chmod 666 ./build/electron_app/py/server/nncd_console/settings/settings.ini
        chmod 666 ./build/electron_app/py/connector/nncd_console/settings/settings.ini
        pushd ./build/electron_app
        npm ci
        npm run linux-gpu-deb
        popd
        mv ./build/electron_app/dist ./
        rm -rf ./build

    - name: upload built gpu deb
      uses: actions/upload-artifact@v4
      with:
        name: linux-gpu-deb
        path: ./dist/*.deb
        retention-days: 1


  app-windows-cpu:
    runs-on: windows-latest
    needs: web-page-linux

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: checkout nnc-desktop
        uses: actions/checkout@v4

      - name: setup for python v3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: setup for Node v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: console-pages
          path: ./console/

      - name: make cpu installer
        shell: cmd
        run: |
          call local_editor\scripts\build_exe.bat "cpu"

      - name: upload built cpu installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-cpu-installer
          path: ./electron_app/dist/NeuralNetworkConsoleDesktop*.exe
          retention-days: 1

  app-windows-gpu:
    runs-on: windows-latest
    needs: web-page-linux

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: checkout nnc-desktop
        uses: actions/checkout@v4

      - name: setup for python v3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: setup for Node v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: console-pages
          path: ./console/

      - name: make gpu installer
        shell: cmd
        run: |
          call local_editor\scripts\build_exe.bat "gpu"

      - name: upload built gpu installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-gpu-installer
          path: ./electron_app/dist/NeuralNetworkConsoleDesktop*.exe
          retention-days: 1


  app-macos-cpu:
    runs-on: macos-latest

    steps:
      - name: checkout nnc-desktop
        uses: actions/checkout@v4

      - name: setup for python v3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: setup for Node v20.15.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: make cpu dmg
        run: |
          bash local_editor/scripts/build_mac_applesilicon.sh

      - name: upload built cpu dmg
        uses: actions/upload-artifact@v4
        with:
          name: macos-cpu-dmg
          path: ./electron_app/dist/*.dmg
          retention-days: 1
