name: Build nncd

on:
  push:
    branches:
    - $default-branch
    - 'release/**'
    - 'feature/**'
  pull_request:
    branches:
    - $default-branch
    - 'release/**'
    - 'feature/**'
  workflow_dispatch:

jobs:
  web-page-linux:
    runs-on: ubuntu-latest

    steps:
    - name: clone nnc-desktop
      uses: actions/checkout@v4

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: restore npm ci cache
      id: npm-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-web-page-linux-${{ hashFiles('local_editor/web_component/*/package-lock.json') }}

    - name: build pages for Linux
      run: |
        mkdir ./build
        cp -r nnc-web/common ./build/
        cp -r nnc-web/web ./build/
        cp -r local_editor ./build/
        cp -rf ./build/local_editor/web_component/local_editor_web/* ./build/web/
        cp -rf ./build/local_editor/web_component/local_editor_editor ./build/new_editor
        cp -rf ./build/local_editor/web_component/local_editor_top ./build/top
        pushd ./build/local_editor
        bash init_build.sh
        popd
        cp -r ./build/top/dist/assets ./build/dist/console/
        cp -r ./build/top/dist/project ./build/dist/console/
        cp -r ./build/local_editor/resource/docs ./build/dist/console/
        cp ./build/common/favicon.ico ./build/dist/console/
        rm -rf ./build/dist/console/lib/dummy
        mv ./build/dist/console ./
        rm -rf ./build

    - name: save npm ci cache
      id: npm-cache-save
      uses: actions/cache/save@v4
      with:
        path: ~/.npm
        key: ${{ steps.npm-cache-restore.outputs.cache-primary-key }}

    - name: upload built pages
      uses: actions/upload-artifact@v4
      with:
        name: console-pages
        path: ./console/
        retention-days: 1


  app-linux-cpu:
    runs-on: ubuntu-latest
    needs: web-page-linux

    steps:
    - name: checkout nnc-desktop
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: console-pages
        path: ./console/

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: setup for python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        pip install -U pip
        pip install nnabla==1.39.0 nnabla_converter==1.39.0
        pip install -r local_editor/requirements.txt
        pip install local_editor/runner_component/tools/console_cli/*.whl

    - name: make cpu deb
      run: |
        mkdir ./build
        cp -r ./electron_app ./build/
        wget -q https://nnabla.org/pkg/nncd-opt-ex.zip -O ./build/electron_app/opt-ex.zip || true
        cp -r ./console ./build/electron_app/
        cp -r ./local_editor/python_modules ./build/electron_app/py/server
        cp -r ./local_editor/runner_component/core ./build/electron_app/py/connector
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/server/
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/connector/
        cp -r ${{ env.pythonLocation }} ./build/electron_app/python_bundles
        rm -f ./build/electron_app/python_bundles/Python-3.*.tgz
        pushd ./build/electron_app
        npm ci
        npm run linux-cpu-deb
        popd
        mv ./build/electron_app/dist ./
        rm -rf ./build

    - name: upload built cpu deb
      uses: actions/upload-artifact@v4
      with:
        name: linux-cpu-deb
        path: ./dist/*.deb
        retention-days: 1


  app-linux-gpu:
    runs-on: ubuntu-latest
    needs: web-page-linux

    steps:
    - name: checkout nnc-desktop
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: console-pages
        path: ./console/

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: setup for python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        echo pythonLocationx
        echo ${{ env.pythonLocation }}
        pip install -U pip
        pip install https://nnabla.org/whl/nnabla_ext_cuda_alllib/nnabla_ext_cuda_alllib-1.39.0-cp310-cp310-manylinux_2_28_x86_64.whl
        pip install nnabla_converter==1.39.0
        pip install -r local_editor/requirements.txt
        pip install local_editor/runner_component/tools/console_cli/*.whl

    - name: make gpu deb
      run: |
        mkdir ./build
        cp -r ./electron_app ./build/
        wget -q https://nnabla.org/pkg/nncd-opt-ex.zip -O ./build/electron_app/opt-ex.zip || true
        cp -r ./console ./build/electron_app/
        cp -r ./local_editor/python_modules ./build/electron_app/py/server
        cp -r ./local_editor/runner_component/core ./build/electron_app/py/connector
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/server/
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/connector/
        cp -r ${{ env.pythonLocation }} ./build/electron_app/python_bundles
        rm -f ./build/electron_app/python_bundles/Python-3.*.tgz
        chmod 666 ./build/electron_app/py/server/nncd_console/settings/settings.ini
        chmod 666 ./build/electron_app/py/connector/nncd_console/settings/settings.ini
        pushd ./build/electron_app
        npm ci
        npm run linux-gpu-deb
        popd
        mv ./build/electron_app/dist ./
        rm -rf ./build

    - name: upload built gpu deb
      uses: actions/upload-artifact@v4
      with:
        name: linux-gpu-deb
        path: ./dist/*.deb
        retention-days: 1


  app-windows-cpu:
    runs-on: windows-latest
    needs: web-page-linux

    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true

    - name: checkout nnc-desktop
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: console-pages
        path: ./console/

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: setup for python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        pip install -U pip
        pip install nnabla==1.39.0 nnabla_converter==1.39.0
        pip install -r local_editor\requirements.txt
        dir local_editor
        dir local_editor\runner_component
        dir local_editor\runner_component\tools
        dir local_editor\runner_component\tools\console_cli
        pip install local_editor\runner_component\tools\console_cli\nnabla_console-10.2.0-py3-none-any.whl

    - name: make cpu installer
      shell: powershell
      run: |
        New-Item -Path ".\build" -ItemType "Directory"
        Copy-Item -Recurse ".\electron_app" ".\build\"
        $ErrorActionPreference = "Continue"
        Invoke-WebRequest -Uri "https://nnabla.org/pkg/nncd-opt-ex.zip" -OutFile ".\build\electron_app\opt-ex.zip"
        $ErrorActionPreference = "Stop"
        Copy-Item -Recurse ".\console" ".\build\electron_app\"
        Copy-Item -Recurse ".\local_editor\python_modules" ".\build\electron_app\py\server"
        Copy-Item -Recurse ".\local_editor\runner_component\core" ".\build\electron_app\py\connector"
        Copy-Item -Recurse ".\local_editor\runner_component\tools\nncd_console" ".\build\electron_app\py\server\"
        Copy-Item -Recurse ".\local_editor\runner_component\tools\nncd_console" ".\build\electron_app\py\connector\"
        Copy-Item -Recurse "${{ env.pythonLocation }}" ".\build\electron_app\python_bundles"
        cd .\build\electron_app
        dir
        tar -czf python_bundles.tgz python_bundles
        Remove-Item -Recurse ".\python_bundles"
        npm ci
        npm run win-cpu-dist
        cd ..\..
        Move-Item -Path ".\build\electron_app\dist" ".\"
        Remove-Item -Recurse ".\build"

    - name: upload built cpu installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-cpu-installer
        path: .\dist\NeuralNetworkConsoleDesktop*.exe
        retention-days: 1

  app-windows-gpu:
    runs-on: windows-latest
    needs: web-page-linux

    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true

    - name: checkout nnc-desktop
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: console-pages
        path: ./console/

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: setup for python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        pip install -U pip
        pip install -U https://nnabla.org/whl/nnabla_ext_cuda_alllib/nnabla_ext_cuda_alllib-1.39.0-cp310-cp310-win_amd64.whl
        pip install nnabla_converter==1.39.0
        pip install -r local_editor\requirements.txt
        pip install local_editor\runner_component\tools\console_cli\nnabla_console-10.2.0-py3-none-any.whl

    - name: make gpu installer
      shell: powershell
      run: |
        New-Item -Path ".\build" -ItemType "Directory"
        Copy-Item -Recurse ".\electron_app" ".\build\"
        $ErrorActionPreference = "Continue"
        Invoke-WebRequest -Uri "https://nnabla.org/pkg/nncd-opt-ex.zip" -OutFile ".\build\electron_app\opt-ex.zip"
        $ErrorActionPreference = "Stop"
        Copy-Item -Recurse ".\console" ".\build\electron_app\"
        Copy-Item -Recurse ".\local_editor\python_modules" ".\build\electron_app\py\server"
        Copy-Item -Recurse ".\local_editor\runner_component\core" ".\build\electron_app\py\connector"
        Copy-Item -Recurse ".\local_editor\runner_component\tools\nncd_console" ".\build\electron_app\py\server\"
        Copy-Item -Recurse ".\local_editor\runner_component\tools\nncd_console" ".\build\electron_app\py\connector\"
        Copy-Item -Recurse "${{ env.pythonLocation }}" ".\build\electron_app\python_bundles"
        cd .\build\electron_app
        echo tar.exe -czf python_bundles.tgz python_bundles
        echo Remove-Item -Recurse ".\python_bundles"
        npm ci
        npm run win-gpu-dist
        cd ..\..
        Move-Item -Path ".\build\electron_app\dist" ".\"
        Remove-Item -Recurse ".\build"

    - name: upload built gpu installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-gpu-installer
        path: .\dist\NeuralNetworkConsoleDesktop*.exe
        retention-days: 1


  app-macos-cpu:
    runs-on: macos-latest
    needs: web-page-linux

    steps:
    - name: checkout nnc-desktop
      uses: actions/checkout@v4

    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: console-pages
        path: ./console/

    - name: setup for Node v20.15.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0

    - name: setup for python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: build nnabla
      run: |
        mkdir -p ./build
        pushd ./build
        wget -q https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.12.tar.gz -O - |tar xzf -
        mkdir protobuf-build
        pushd protobuf-build
        cmake -Dprotobuf_BUILD_TESTS=OFF ../protobuf-21.12/cmake
        make -j8
        popd
        git clone https://github.com/sony/nnabla.git
        mkdir nnabla-build
        pushd nnabla-build
        python -m venv nnabla-venv
        . nnabla-venv/bin/activate
        python -m pip install -U pip
        perl -i -pe 's/^Cython$/Cython==3.0.10/g' ../nnabla/python/requirements.txt
        perl -i -pe 's/^numpy$/numpy==1.26.4/g' ../nnabla/python/requirements.txt
        python -m pip install -U -r ../nnabla/python/requirements.txt
        python -m pip install -U -r ../nnabla/python/setup_requirements.txt
        cmake -DPROTOC_COMMAND=$(readlink -f ../protobuf-build/protoc) ../nnabla
        make -j8
        deactivate
        popd
        popd
        mv ./build/nnabla-build/dist/nnabla-*.whl ./
        mv ./build/nnabla-build/dist/nnabla_converter-*.whl ./
        rm -rf ./build

    - name: install python packages
      run: |
        pip install -U pip
        pip install ./nnabla-*.whl ./nnabla_converter-*.whl
        pip install -r local_editor/requirements.txt
        pip install local_editor/runner_component/tools/console_cli/*.whl

    - name: make cpu dmg
      run: |
        mkdir -p ./build

        cp -r ./electron_app ./build/
        wget -q https://nnabla.org/pkg/nncd-opt-ex.zip -O ./build/electron_app/opt-ex.zip || true
        cp -r ./console ./build/electron_app/
        cp -r ./local_editor/python_modules ./build/electron_app/py/server
        cp -r ./local_editor/runner_component/core ./build/electron_app/py/connector
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/server/
        cp -r ./local_editor/runner_component/tools/nncd_console ./build/electron_app/py/connector/
        cp -r ${{ env.pythonLocation }} ./build/electron_app/python_bundles
        rm -f ./build/electron_app/python_bundles/Python-3.*.tgz
        pushd ./build/electron_app
        npm ci
        npm run mac-dist
        popd
        mv ./build/electron_app/dist ./
        rm -rf ./build

    - name: upload built cpu dmg
      uses: actions/upload-artifact@v4
      with:
        name: macos-cpu-dmg
        path: ./dist/*.dmg
        retention-days: 1
